# Generated by Django 2.2 on 2020-08-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0002_auto_20200813_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='product_code',
        ),
    ]
