# Generated by Django 2.2 on 2020-09-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0006_customerorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='price',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='quantity',
            field=models.CharField(max_length=500),
        ),
    ]
