# Generated by Django 2.2 on 2020-09-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0007_auto_20200908_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
