# Generated by Django 2.2 on 2020-09-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0008_auto_20200908_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
