# Generated by Django 2.2 on 2020-09-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0011_remove_customerorders_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorders',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
