# Generated by Django 2.2 on 2020-09-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0012_customerorders_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
